name: vpn_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.7.2
  hugeicons: ^0.0.11
  get_it: ^8.0.3
  equatable: ^2.0.7
  lottie: ^3.1.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  leak_tracker: ^10.0.2
  leak_tracker_flutter_testing: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/lottie/

